# -*- coding: utf-8 -*-
"""Sem13_correlacion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKEvYrmswqqiSxhjTzQ-Y1S2_FZY_23Y
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("Estadistica").getOrCreate()

spark

data_ayf = [(5,1),(1,5),(4,2),(1,1),(2,4),(4,2),(5,1),(4,2),(2,4),(1,5),(3,3),(2,4),(4,2),(1,5),(1,1)]
columns_AyF = ["Asistencias","Faltas"]
variable_corr = spark.createDataFrame(data_ayf,columns_AyF)

correlacion = variable_corr.select(corr(col("Asistencias"),col("Faltas")).alias("correlacion")).collect()[0]["correlacion"]

print("La correlacion es:",correlacion)